-- +goose Up
CREATE TABLE Feeds (
  ID UUID PRIMARY KEY,
  user_id UUID REFERENCES Users(ID) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL,  
  updated_at TIMESTAMP NOT NULL  
);

-- +goose Down
DROP TABLE IF EXISTS Feeds;